version: '3'

services:
  app:
    container_name: docker-node-mongo
    restart: always
    build: .
    ports:
      - '9000:9000'
    depends_on:
      - mongodb
    environment:
      DB_CONNECT: mongodb://root:rootpassword@mongodb:27017
  mongodb:
    container_name: mongodb
    image: mongo:6
    environment:
      MONGO_INITDB_DATABASE: FoodDeliveryDB
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data_container_x:/data/db

volumes:
  mongodb_data_container_x: